version: '3'
services:
  api:
    build: 
      context: ./api
    env_file: .env
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - "./api/src:/app/node/src"
      - "./api/node_modules:/app/node/node_modules"
    depends_on:
      - mongo
    networks:
      - "net"
    command: "yarn dev"

  mongo:
    image: mongo:4.2-bionic
    ports:
      - "27017:27017"
    networks:
      - "net"

networks:
  net:
    driver: bridge
