version: '3'
services:
  api:
    build: 
      context: ./api
    env_file: .env
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - "./api/src:/app/node/src"
      - "./api/node_modules:/app/node/node_modules"
    networks:
      - "net"
    command: "yarn dev"

  mongo1:
    image: mongo:4.2-bionic
    ports:
      - "27017:27017"
    networks:
      - "net"
    volumes:
      - "./data/db:/data/db"
    command: "mongod --replSet mongo-set"

  mongo2:
    image: mongo:4.2-bionic
    ports:
      - "27018:27017"
    networks:
      - "net"
    volumes:
      - "./data/db2:/data/db"
    command: "mongod --replSet mongo-set"

networks:
  net:
    driver: bridge
