version: '3'
services:
  api:
    build: 
      context: ./api
    env_file: .env
    expose:
      - "3000"
    ports:
      - "3000:3000"
   networks:
      - "net"
    command: "yarn start"

  mongo:
    image: mongo:4.2-bionic
    ports:
      - "27017:27017"
    networks:
      - "net"
    volumes:
      - "./data/db:/data/db"
    command: "mongod --replSet mongo-set"

networks:
  net:
    driver: bridge
